/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2025-07-25 13:14:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.navbar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NavProvider_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/HealthSure/Central-Project-Repo-HMS--sourabh/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/HealthSureClient/WEB-INF/lib/jsf-impl-2.2.14.jar!/META-INF/html_basic.tld", Long.valueOf(1479140598000L));
    _jspx_dependants.put("/WEB-INF/lib/jsf-impl-2.2.14.jar", Long.valueOf(1750870878935L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fgraphicImage_0026_005fstyleClass_005fname_005flibrary_005falt_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fh_005fgraphicImage_0026_005fstyleClass_005fname_005flibrary_005falt_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fh_005fgraphicImage_0026_005fstyleClass_005fname_005flibrary_005falt_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/HealthSureClient/resources/css/navbar.css\" />\r\n");
      out.write("<nav id=\"navbar\" class=\"navbar navbar-scrolled\"> <!-- Removed navbar-transparent -->\r\n");
      out.write("    <div class=\"navbar-container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- LOGO + NAME -->\r\n");
      out.write("        <div class=\"navbar-logo\">\r\n");
      out.write("        \t<a href=\"/HealthSureClient/home/Home.jsf\" class=\"logo-link\">\r\n");
      out.write("            ");
      if (_jspx_meth_h_005fgraphicImage_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </a>\r\n");
      out.write("            <span class=\"brand-name\">HealthSure</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- PROVIDER NAV LINKS -->\r\n");
      out.write("        <ul class=\"nav-links\">\r\n");
      out.write("            <li><a href=\"Provider.jsf\" class=\"nav-link\">Dashboard</a></li>\r\n");
      out.write("            <li><a href=\"appointments.jsf\" class=\"nav-link\">Appointments</a></li>\r\n");
      out.write("            <li><a href=\"patients.jsf\" class=\"nav-link\">Patients</a></li>\r\n");
      out.write("            <li><a href=\"ClaimAction.jsf\" class=\"nav-link\">Insurance Claim</a></li>\r\n");
      out.write("            <li><a href=\"services.jsf\" class=\"nav-link\">Add Doctors</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"profile-section\">\r\n");
      out.write("\t\t    ");
      if (_jspx_meth_h_005fgraphicImage_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    <a href=\"Profile.jsf\" class=\"view-profile-btn\">View Profile</a>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_h_005fgraphicImage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:graphicImage
    com.sun.faces.taglib.html_basic.GraphicImageTag _jspx_th_h_005fgraphicImage_005f0 = new com.sun.faces.taglib.html_basic.GraphicImageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fgraphicImage_005f0);
    try {
      _jspx_th_h_005fgraphicImage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fgraphicImage_005f0.setParent(null);
      // /navbar/NavProvider.jsp(10,12) name = library type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f0.setLibrary(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(10,12) 'media'",_jsp_getExpressionFactory().createValueExpression("media",java.lang.String.class)));
      // /navbar/NavProvider.jsp(10,12) name = name type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f0.setName(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(10,12) 'images/Logo.jpg'",_jsp_getExpressionFactory().createValueExpression("images/Logo.jpg",java.lang.String.class)));
      // /navbar/NavProvider.jsp(10,12) name = alt type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f0.setAlt(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(10,12) 'HealthSure Logo'",_jsp_getExpressionFactory().createValueExpression("HealthSure Logo",java.lang.String.class)));
      // /navbar/NavProvider.jsp(10,12) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f0.setStyleClass(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(10,12) 'logo-img'",_jsp_getExpressionFactory().createValueExpression("logo-img",java.lang.String.class)));
      _jspx_th_h_005fgraphicImage_005f0.setJspId("jsp_728926917_0");
      int _jspx_eval_h_005fgraphicImage_005f0 = _jspx_th_h_005fgraphicImage_005f0.doStartTag();
      if (_jspx_th_h_005fgraphicImage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fgraphicImage_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fgraphicImage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:graphicImage
    com.sun.faces.taglib.html_basic.GraphicImageTag _jspx_th_h_005fgraphicImage_005f1 = new com.sun.faces.taglib.html_basic.GraphicImageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fgraphicImage_005f1);
    try {
      _jspx_th_h_005fgraphicImage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fgraphicImage_005f1.setParent(null);
      // /navbar/NavProvider.jsp(25,6) name = library type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f1.setLibrary(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(25,6) 'media'",_jsp_getExpressionFactory().createValueExpression("media",java.lang.String.class)));
      // /navbar/NavProvider.jsp(25,6) name = name type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f1.setName(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(25,6) 'images/defaultProfile.jpg'",_jsp_getExpressionFactory().createValueExpression("images/defaultProfile.jpg",java.lang.String.class)));
      // /navbar/NavProvider.jsp(25,6) name = alt type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f1.setAlt(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(25,6) 'Profile Avatar'",_jsp_getExpressionFactory().createValueExpression("Profile Avatar",java.lang.String.class)));
      // /navbar/NavProvider.jsp(25,6) name = styleClass type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fgraphicImage_005f1.setStyleClass(new org.apache.jasper.el.JspValueExpression("/navbar/NavProvider.jsp(25,6) 'profile-avatar'",_jsp_getExpressionFactory().createValueExpression("profile-avatar",java.lang.String.class)));
      _jspx_th_h_005fgraphicImage_005f1.setJspId("jsp_728926917_1");
      int _jspx_eval_h_005fgraphicImage_005f1 = _jspx_th_h_005fgraphicImage_005f1.doStartTag();
      if (_jspx_th_h_005fgraphicImage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fgraphicImage_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
